Update local.conf
sabaton-rs/sabaton-ndk pull request #8
Opened 2023-11-14 08:47 UTC by acsia2mohin

whitelist a commercial license and SDKPATHINSTALL is set to /opt/sabaton/<ndk_version>

2023-11-14 08:48 UTC, acsia2mohin commented
whitelist a commercial license and SDKPATHINSTALL is set to /opt/sabaton/<ndk_version>

2023-11-14 08:50 UTC, sjames requested changes

2023-11-14 08:50 UTC, sjames commented on yocto/meta-sabaton/conf/local.conf
> +LICENSE_FLAGS_ACCEPTED += "commercial"
why do we need the commercial flags? Which package triggered this?

2023-11-14 16:12 UTC, acsia2mohin commented on yocto/meta-sabaton/conf/local.conf
> +LICENSE_FLAGS_ACCEPTED += "commercial"
ffmpeg_5.1.2.bb pkg has LICENSE_FLAGS = "commercial".So to compile ffmpeg need to accept this license.

2023-11-25 10:02 UTC, sjames approved these changes

2023-11-25 10:02 UTC, merged